### ISSUE TITLE
"Scroll hello, world" shows only "hello"

### ISSUE THREAD

**Issue by mobluse** [MrYsLab/s2m#10]
`Scroll hello, world` shows only "hello". I discovered this bug when I read the source code of s2mb.py. One way to solve this is to scroll from the original string.
I changed the code on line 99-101 to:
```
        # scroll text command
        elif cmd_id == 's':
            display.scroll(cmd[2:], wait=False)
```

**Comment by MrYsLab** [comment]
Thanks. The fix will be slightly different. It will be incorporated into v1.11.
```
        elif cmd_id == 's':
            display.scroll(str(cmd_list[1]), wait=False)
```
