### ISSUE TITLE
Why do some words in the blocks begin with a lower case letter?

### ISSUE THREAD

**Issue by mobluse** [MrYsLab/s2m#13]
Why do "pressed", "right", "left", "up", "down" in the s2m blocks for English begin with lower case letter?

**Comment by MrYsLab** [comment]
I originally had them in upper case but changed it all to lower case because I thought it looked strange. 

Please let me know if this is causing an issue for you or just a question out of curiosity.

**Comment by mobluse** [comment]
The question was out of curiosity. In Scratch in English all words except "I" are in all lower case, but in s2m some words begin with an upper case letter.

Also, in Scratch "x" and "y" are followed by ":". 

Also, in BBC micro:bit "x" and "y" is rather "c" and "r", i.e. column and row. 

These are only cosmetic issues, but one has to be able to explain them to users.

**Comment by MrYsLab** [comment]
There is no problem in asking questions. The way I am spelling things does not conform to the way Scratch does in their blocks. At this point, I am going to leave things as is, but Scratch 3.0 is coming soon, and I will revisit this when 3.0 extensions get underway. 

I am closing this issue, but feel free to make any comments and I will see them here.

Thanks.
