### ISSUE TITLE
Current version of S2mb.py not working for input

### ISSUE THREAD

**Issue by sobreira** [MrYsLab/s2m#22]
Hi Alan, 
I realized that after last update the analog and digital pins are not sending data to microbit - at least for me.
If I switch the file s2mb.py from 07 December 2017 (the first version I got), the microbit receives data in a properly way.
Please find enclosed the version that is working for me and the current one that doesn't - same I got in Github

I am testing with an LDR: (but connected to a microbit - of course ;o)
![image](https://user-images.githubusercontent.com/5200448/38710216-81e65a0c-3e95-11e8-81ac-ca4d46674f5a.png)

P.S Looks that the pip installer cames with s2mb2.py which is not avalaible from Github

[s2mb_not_working.zip](https://github.com/MrYsLab/s2m/files/1905363/s2mb_not_working.zip)
[s2mb_working.zip](https://github.com/MrYsLab/s2m/files/1905364/s2mb_working.zip)

**Comment by MrYsLab** [comment]
Thanks for letting me know, please try out the latest version of [s2mb_min.py](https://github.com/MrYsLab/s2m/blob/master/s2m/micro_bit_scripts/s2mb_min.py) and let me know if that solves the problem. Thanks.

**Comment by sobreira** [comment]
Hi Alan, I have tried but no success so far.
If I keep only the indicated lines, only, removing the rest, everything is fine again.

![image](https://user-images.githubusercontent.com/5200448/38748137-87c3a7de-3f23-11e8-9476-a1af2ec9454d.png)

Looks that the current code send information just once to Scratch, when communication starts between Scratch and micro:bit a value is sent and just it, no refresh anymore.

Thanks!

**Comment by MrYsLab** [comment]
I think I have a fix. I am going to spend a few more hours testing and hopefully should be able to publish the fixes in the next couple of days. Thanks for your patience.

**Comment by MrYsLab** [comment]
I published version 2.6 which I believe solves the issue. Please test and let me know if the issue has been resolved for you.  Thanks.

**Comment by sobreira** [comment]
Thanks a lot by the effort in getting it solved.

Now looks that the input is getting the data in a properly way, but I realized another issue.
As soon as I select the same pin as an output, the input doesn't work anymore(which makes sense). However if I remove the block notthing happen, the input pin cannot be read anymore. To work again the microbit must be reset.
Looks that the output block remains valid even when it is removed.

![microbit_scratch_input](https://user-images.githubusercontent.com/5200448/38770762-42ee9152-3fee-11e8-9dc9-119d75df48c4.gif)

I have made a test and worked after it, but as I am not a Python expert, I have no idea about collateral effect of this measure.

I have copied the line 42 and place it in the line 247 `(digital_outputs = [False, False, `False]``

Doing this the system could read the input pin again, but... not sure this is the right approach.

Thanks!

**Comment by MrYsLab** [comment]
Thanks and you are correct about how  the pins now operate. I had documented this [here](https://mryslab.github.io/s2m/blocks/#digital-write)

The way the micro:bit works, is that if you set a pin as a digital output, set it high, and then do a digital read on that pin, it will reset the pin as a digital input and will set the pin low. I believe your fix will cause an output pin set to high to "flash" and not stay active high.

The better solution would be to add a new block that sets the pin mode, but that would make things more complicated for the user, and old scratch projects might no longer work.

I am going to close the issue, but if you have any other questions about this issue, you can comment here and I will see it, or feel free to open a new issue.

Thanks
