### ISSUE TITLE
Update source code to make it compatible with Scratch 3.0 javascript extension mechanism

### ISSUE THREAD

**Issue by sergiogonzalez** [MrYsLab/s2m#24]
Hey @MrYsLab 
It seems that the HTTP extension method will no longer be available in Scratch 3.0 that is supposed to be released by August 2018.
Do you have any plan to update your code to make it compatible with Scratch 3.0 javascript extensions?
Thanks!

**Comment by MrYsLab** [comment]
Hi @sergiogonzalez 
   There has also has been some talk that 3.0 will come with a micro:bit extension as a standard part of the release.
   If Scratch comes out with a useful extension for micro:bit that works reliably with all computing platforms (Windows, Linux, Raspberry Pi, Mac), then I will not be coming out with a competing extension. However, if 3.0 has very limited miro:bit capabilities or is buggy, then I will develop a 3.0 extension.
   I am closing this as an issue, but feel free to make further comments. I will see them and we can continue the conversation if you like.
  
Alan
