### ISSUE TITLE
Can s2m support the existed scratch project?

### ISSUE THREAD

**Issue by andy8050802** [MrYsLab/s2m#25]
Thanks for ur help first
I have a old project ,and I want to improve it by micro:bit 
Have some methods to connect extension?(I can only connect by a new project)
Hope that you know what I said thanks!

**Comment by MrYsLab** [comment]
If I understand your question, you have an older s2m project that is no longer working. Is that correct?

**Comment by andy8050802** [comment]
an older pure "scratch" project. 
can I add the extension lately to the project that didn't connect s2m at first?

**Comment by andy8050802** [comment]
btw, I copy the project to a new file, and It's already fine. 
I still curious, thanks a lots for ur tool and help!

**Comment by MrYsLab** [comment]
You cannot add the extension blocks to an existing project. This how the Scratch team designed the extension mechanism, and unfortunately, it cannot be changed.

I am closing this issue, but if you have any further comments or questions, you can add them here or open up a new issue.
