### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by sobreira** [MrYsLab/s2m#26]
Hi, following a spanish version for motion project.
[motion_es.zip](https://github.com/MrYsLab/s2m/files/1926145/motion_es.zip)

I have made a slight change in the spanish extension, changing the name from s2m to s2m-es, hope it's not an issue to suggest it as I was not the translator.
[s2m_es.zip](https://github.com/MrYsLab/s2m/files/1926147/s2m_es.zip)

Thanks!

**Comment by MrYsLab** [comment]
Thanks for the changes and motion example. There were some slight problems in the example that I corrected. 
Version 2.8 incorporates the changes.
