### ISSUE TITLE
blocks not visible

### ISSUE THREAD

**Issue by alb4h** [MrYsLab/s2m#27]
I've just installed s2m for the first time and when I type s2m in the cmd window, Scratch opens but there are no Microbit related blocks in the 'more block section.   I have a Microbit connected and I don't see any errors when trying to launch s2m:  

I installed everything following the directions here:  
https://mryslab.github.io/s2m/usage/#starting-s2m-on-windows-mac-and-linux
I'm running windows 10. 

![image](https://user-images.githubusercontent.com/6170178/39151910-37e5a3c0-470c-11e8-8499-16b5e704aaf8.png)

**Comment by MrYsLab** [comment]
It looks like you are using an older version of the micro:bit script. Please install this version on your micro:bit https://github.com/MrYsLab/s2m/blob/master/s2m/micro_bit_scripts/s2mb_min.py

If that doesn't solve your problem , please try a manual start described here:
https://mryslab.github.io/s2m/usage/#manually-starting-s2m-and-scratch

**Comment by alb4h** [comment]
Thanks. I went ahead and did the manual start before I heard back from you
and the blocks showed up, however the scratch program didn't recognize any
inputs - tilts, button presses, etc.

I will try the newer script tomorrow.

Ann

**Comment by MrYsLab** [comment]
Please let me know if changing the script solves your problem. I realized that I did not update the User's Guide with the latest script and that may have caused the issue for you. I apologize for that and the Guide now shows the latest script.

**Comment by alb4h** [comment]
Hi Alan - I still don't see the blocks.

**Comment by MrYsLab** [comment]
Could you please try typing in:
```
s2m -d true
```
and send me a screenshot of the results.

When I run this command, this is what I see:

![screenshot from 2018-04-25 16-04-03](https://user-images.githubusercontent.com/5189838/39270593-8f80de8a-48a4-11e8-9011-9ee22e81ade2.png)

The username should be yours, but everything else should be similar.

**Comment by alb4h** [comment]
looks like my s2m is version 2.8

**Comment by MrYsLab** [comment]
That should not have mattered. Is the path the same even though the version is different?

**Comment by MrYsLab** [comment]
@alb4h Are you still having the issue? If so, some questions:
1. Did you use pip to install s2m?
2. If you did use pip, did you use the --user option? That will install files in a roaming directory and s2m does use roaming directories. 
3. Could you please provide a screenshot of the console output after running 
```
s2m -d true
```

**Comment by alb4h** [comment]
I am. I sent a screen shot on the email a couple days ago but will resend
again this afternoon when I am at a computer.

I did use pip but not -user.

**Comment by MrYsLab** [comment]
@alb4h Just to let you know, if you sent the screenshot, I did not receive it.

**Comment by alb4h** [comment]
Hmm it shows up in my email. I'll resend tonight.

**Comment by MrYsLab** [comment]
GitHub is kind of picky when it comes to sending images. I find the easiest way is to go into the GitHub issues page (here is the link for your issue: https://github.com/MrYsLab/s2m/issues/27), and then attach the file as per instructions in the bottom of the comment - I did a screenshot of what I am referring to
_________________________
Screenshot follows:
__________________________
![screenshot from 2018-04-30 12-39-05](https://user-images.githubusercontent.com/5189838/39438863-8f7b3fa2-4c73-11e8-9540-699782ba373d.png)

**Comment by MrYsLab** [comment]
I am not sure if you had a chance to resend or not, but in the meantime, here is something else to check:

Make sure that the Python paths have been set correctly. If you check your environment Path variables, you should see two entries that look something like this:
```
C:\Users\Alan\AppData\Local\Programs\Python\Python36\Scripts\
C:\Users\Alan\AppData\Local\Programs\Python\Python36\
```
These variables are automatically set if you selected "Add Python 3.x to PATH when you installed Pytnon.
There is a checkbox at the bottom of the Python install dialog to do so:

![python2](https://user-images.githubusercontent.com/5189838/39481024-05c7265c-4d38-11e8-9e8e-91ee7831f46e.png)

Any version of Python from 3.5 forward should work.

If you wish to send me an email directly, you can find my email address [here](https://mryslab.github.io/s2m/#comments-or-questions)

**Comment by MrYsLab** [comment]
I am closing this issue since this the only report I have received about it. If you are still having this issue please provide the information I requested and I will gladly reopen it and will try to resolve it.
