### ISSUE TITLE
Update on pt-br

### ISSUE THREAD

**Issue by sobreira** [MrYsLab/s2m#28]
Hi, @MrYsLab I just send an update from pt-br transalation.
I realized that I forgot to translate one block - Value instead of Valor.

I´d appreciate if you can update it in future realeases.

Thanks

[pt-br.zip](https://github.com/MrYsLab/s2m/files/1944489/pt-br.zip)

**Comment by MrYsLab** [comment]
No problem. I will update and publish soon.

**Comment by MrYsLab** [comment]
I added your updates and published them as version 2.9. Thanks.
