### ISSUE TITLE
Conection lost after include tilt function

### ISSUE THREAD

**Issue by sobreira** [MrYsLab/s2m#29]
Hi @MrYsLab, I have tested the following sketch:
![image](https://user-images.githubusercontent.com/5200448/39213091-fedf5ce8-47e6-11e8-97c7-70748919f2c8.png)

I am using the last version of your program.
Eveerything works fine until I tilt the device.
In that moment the green circle became red.
looking to DOS it´s exactly the same as before.
![image](https://user-images.githubusercontent.com/5200448/39213321-a02307f8-47e7-11e8-8e42-621fb4089b89.png)

How it works for you?

Thanks!

**Comment by MrYsLab** [comment]
Yes, I see the same. If you add a small delay it should solve the problem. I will see if I can remove the need for the delay, but if not I will update the guide.

![capture](https://user-images.githubusercontent.com/5189838/39219939-c58a15ea-47fb-11e8-9760-69bd230fed30.PNG)

**Comment by sobreira** [comment]
Thanks a lot!

2018-04-24 21:12 GMT-03:00 Alan Yorinks <notifications@github.com>:

**Comment by MrYsLab** [comment]
I added a "Troubleshooting" section to the user's guide. https://mryslab.github.io/s2m/troubleshooting/
