### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'g' 

### ISSUE THREAD

**Issue by rsrini7** [MrYsLab/s2m#30]
I am getting below exception when executing s2m.

s2m version 2.11 Copyright(C) 2018 Alan Yorinks  All rights reserved.

Python Version 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:23:52) [MSC v.1900 32 bit (Intel)]
Autodetecting serial port. Please wait...
Using COM Port:com3

s2mb Version: v

Auto launching Scratch
Starting HTTP Server!
Use <Ctrl-C> to exit the extension.
Please make sure you save your Scratch project BEFORE pressing Ctrl-C.

Exception happened during processing of request from ('127.0.0.1', 44366)
Traceback (most recent call last):
  File "i:\anaconda3-32\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "i:\anaconda3-32\lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "i:\anaconda3-32\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "i:\anaconda3-32\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "i:\anaconda3-32\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "i:\anaconda3-32\lib\http\server.py", line 406, in handle_one_request
    method()
  File "i:\anaconda3-32\lib\site-packages\s2m\s2m_http_server.py", line 76, in do_GET
    self.send_resp(self.s2m.handle_poll())
  File "i:\anaconda3-32\lib\site-packages\s2m\s2m.py", line 368, in handle_poll
    resp = self.build_poll_response(reply)
  File "i:\anaconda3-32\lib\site-packages\s2m\s2m.py", line 458, in build_poll_response
    x = int(data_list[0])
ValueError: invalid literal for int() with base 10: 'g'

**Comment by MrYsLab** [comment]
Do you have the micro:bit loaded with the correct script? The version number for s2mb in your dump above is not correct. Here is what I get when I start s2m:
```

s2m version 2.11 Copyright(C) 2018 Alan Yorinks  All rights reserved.

Python Version 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Autodetecting serial port. Please wait...
Using COM Port:com7

s2mb Version: s2mb.py Version 1.10 14 April 2018

Auto launching Scratch
Starting HTTP Server!
Use <Ctrl-C> to exit the extension.
Please make sure you save your Scratch project BEFORE pressing Ctrl-C.
```
I loaded the script into the micro:bit by copying [s2mb_min.py](https://github.com/MrYsLab/s2m/blob/master/s2m/micro_bit_scripts/s2mb_min.py) into the mu editor and using it to flash the micro:bit.

I also flashed using [uflash](https://github.com/ntoll/uflash) and that too was successful.

**Comment by rsrini7** [comment]
loaded the script into the micro:bit by copying s2mb_min.py into the mu editor and using it to flash the micro:bit. - issue got resolved. Thanks.

**Comment by MrYsLab** [comment]
I am glad it is working for you. Thanks for letting me know.
