### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SYtang98** [MrYsLab/s2m#31]
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/36919402/43684447-a5a8ebf2-98d2-11e8-8c12-fd3695a3787e.png">
Hi, I am trying to use a Mircobit sender to send accelerometer XYZ values to another Mircobit receiver.  Mircobit sender sent a fixed string '32,112,-976,False,False,0,0,0,0,0,0,' to the receiver, however it keeps on producing the above error. 

upon reading line 499 of [https://github.com/MrYsLab/s2m/blob/c5ddaaf0e07b6ba6b7d8c88391893c2e7ec1bd0e/s2m/s2m.py](url) it seems like the code didn't manage to process my data_list[8] value. 

Please assist, IM LOST.

**Comment by MrYsLab** [comment]
I don't understand. To use s2m, [s2mb_min.py](https://github.com/MrYsLab/s2m/blob/master/s2m/micro_bit_scripts/s2mb_min.py) must be installed on the micro:bit and communication between the micro:bit and the computer running Scratch is accomplished through a USB serial cable. The s2m program does not support communication between 2 micro:bits.

Please explain exactly what you mean by "I am trying to use a Mircobit sender to send accelerometer XYZ values to another Mircobit receiver". If you are trying to use the micro:bit radio interface somehow with s2m, s2m does not support the radio interface.

**Comment by MrYsLab** [comment]
I am going to close this issue. If you have any questions or need some help, please post here and I will reply. If you still feel this is a bug, please let me know, and if I can always reopen the issue.
