### ISSUE TITLE
Can't detect serial port

### ISSUE THREAD

**Issue by reddwarfff** [MrYsLab/s2m#33]
I am having trouble getting s2m to run on Windows 10. Followed install instructions with install of Python 3.7, the Mu editor but at command prompt 's2m', I get the error message 'Failed to detect serial port. Check cable or connection'. I have successfully installed and run s2m on a pi but want it on laptop for convenience but cannot get past this step. Microbit is attached to COM 1. Any help gratefully received.

**Comment by MrYsLab** [comment]
Normally COM 1 is reserved by Windows. If you open up the Windows device manager, and go to the ports tab, do you see something like this:
![screenshot from 2018-09-28 09-34-47](https://user-images.githubusercontent.com/5189838/46212266-8d6f4d00-c303-11e8-900d-7ba43f010a14.png)

The micro:bit is indicated as an mbed device and on my computer is on COM7.

If you are seeing the micro:bit as COM1, then could you please try starting s2m with the following command line:
```
s2m -p COM1
```
Does that work?

**Comment by reddwarfff** [comment]
Ah, no it's not listing the microbit, although allowed me to flash the program from Mu editor. What do i do?

**Comment by reddwarfff** [comment]
It lists the microbit as portable device but doesn't assign it a port

![image](https://user-images.githubusercontent.com/30109244/46213205-e2c15380-c32f-11e8-8594-4b135f83cbc1.png)

**Comment by MrYsLab** [comment]
I have not encountered a portable device before, so I am not sure what to do in this case. It appears that this may be an issue with some PCs and Windows 10. Here is [link](https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware-winpc/windows-10-usb-doesnt-recognize-portable-device/8d84cf7b-eb41-431c-b243-a0d20e36d069) to an article describing this.

This [link](https://www.cnet.com/how-to/windows-10-settings-menu-the-devices-tab/) describes how to manually add a device, but I am not sure if this will fix your issue or not.

Lastly, you may need to install an [mbed serial driver](https://os.mbed.com/docs/latest/tutorials/windows-serial-driver.html), although supposedly this is not necessary for Windows 10.

Please let me know if any of this helps to solve your issue. I will continue to look for a possible solution.

**Comment by MrYsLab** [comment]
Here is another [link](https://thinksmartbox.com/answer/changing-the-com-port-for-a-usb-device/) explaining how to manually set a com port. Again not sure if this will lead anywhere since I cannot test it here.

**Comment by MrYsLab** [comment]
Yet another thought. I am not sure if Bluetooth devices are considered portable devices, but you may try [disabling Bluetooth](https://uk.answers.acer.com/app/answers/detail/a_id/36948/~/windows-10%3A-enable-or-disable-bluetooth) if you have it enabled.

**Comment by reddwarfff** [comment]
ok tried disabling Bluetooth, unanle to asign COM port to portable device, but the downloaded mbed serial driver which now shows as below but same result when typing s2m into command prompt. Also tried s2m -p COM3
![image](https://user-images.githubusercontent.com/30109244/46233003-0e146480-c369-11e8-9591-a8dc32688e87.png)

**Comment by reddwarfff** [comment]
Forgot to say the Microbit is still showing in portable drivers

**Comment by reddwarfff** [comment]
Solved! After downloading mbed serial driver, I then reflashed code to the Microbit and s2m now works from the command line. Thank you so much for your help!

**Comment by MrYsLab** [comment]
Glad you got it going. If you have any additional questions about this issue, you can post here and I will see the post even though it is closed. If you have any additional issues, please feel free to enter a new issue.
