### ISSUE TITLE
cannot connect microbit in windows. it is red, why?

### ISSUE THREAD

**Issue by junhuanchen** [MrYsLab/s2m#34]
![1](https://user-images.githubusercontent.com/32978053/50384322-3b6d7600-06fe-11e9-828d-5c26e0fb1cc5.png)
![2](https://user-images.githubusercontent.com/32978053/50384323-3b6d7600-06fe-11e9-9510-23052527f6be.png)

try install https://scratch.mit.edu/help/studio/tips/howto/wedo2win-1/

but still cant connect.

look at this scratch2.0 never request(http://localhost:50209/poll).

**Comment by MrYsLab** [comment]
@junhuanchen I am sorry you are having problems with s2m. The s2m program works only with the off-line version of Scratch and it connects to the micro:bit using a USB cable. The device manager that the Scratch team provides is not compatible with s2m. This incompatibility is a choice of the Scratch and not mine.

To try and help you, I have some questions:

1. Are you connecting your micro:bit with a USB cable to your computer?
2. Did you load the special micro:bit program on to your micro:bit? Instructions for doing this can be found [here](https://mryslab.github.io/s2m/install/#installing-the-s2m-microbit-script-on-the-microbit)
3. What operating system are you using - Windows, macOS or Raspberry Pi?

**Comment by junhuanchen** [comment]
1.sure
2.Because I confirmed that the underlying can enter g instructions to get the data, but also confirmed the pages localhost can get data, so I think, is scratch2.0 no communication with http://localhost:50209/poll
3.in winodws10 python3.5

**Comment by MrYsLab** [comment]
We need to make sure that the proper driver is installed and that s2m is selecting the correct com port.

Please do the following:
1. Plug the micro:bit into your Windows computer.
2. Open the Windows Device Manager and expand the Ports tab
![image](https://user-images.githubusercontent.com/5189838/50402749-c84c1a00-0766-11e9-8774-318a253e4022.png)
3. If you do not see the "mbed Serial Port", you will need to install the [mbed serial driver](https://os.mbed.com/docs/latest/tutorials/windows-serial-driver.html). 
4. Once you are able to see the "mbed Serial Port", look at the COM port that windows assigned. In the screenshot above this is COM7. Your COM port may be different.
5. When you start s2m, the COM port is identified on the console:
![image](https://user-images.githubusercontent.com/5189838/50402818-82dc1c80-0767-11e9-99cd-2a2b3599c886.png)
In this Screenshot, the COM port is com4.  If the com port that is listed in the device manager is different than the com port that s2m chose, then you will need to manually identify the correct com port when starting s2m. To do, use the -p option. This is [documented here](https://mryslab.github.io/s2m/usage/#command-line-options).
6. If the com ports are correct but Scratch still does't connect, try starting in a manual mode. This is [documented here](https://mryslab.github.io/s2m/usage/#manually-starting-s2m-and-scratch).

Please let me know if any of this solved your problem. Thanks.

**Comment by junhuanchen** [comment]
well, you known that i can get http://localhost:50209/poll data. so i think this is windows bugs. 
but it can running in linux, so keep watching.
