### ISSUE TITLE
Modify Write Pixel block to allow for setting its parameters with variables

### ISSUE THREAD

**Issue by MrYsLab** [MrYsLab/s2m#8]
Change the block from 3 drop-down menus to explicit numerical values. This will allow the user to control the parameters with variables.

**Comment by MrYsLab** [comment]
@champierre Release 1.10 implements the enhancement.

**Comment by mobluse** [comment]
Scratch 2 have some blocks that have drop down menus and also can take variables: e.g. `set instrument to ()`. Could this not also be possible for this extension?

**Comment by MrYsLab** [comment]
You are correct about the blocks in Scratch 2, but unfortunately, they don't offer a similar construct for the extension blocks.
